start-at-login = true
accordion-padding = 8

[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]

# LAYOUT
alt-slash  = 'layout tiles horizontal vertical'
alt-period = 'layout accordion horizontal vertical'
alt-comma  = 'fullscreen'

# FOCUS
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# MOVE
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# RESIZE
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# WORKSPACES
alt-m = 'workspace M'
alt-p = 'workspace P'
alt-w = 'workspace W'

alt-shift-m = 'move-node-to-workspace M'
alt-shift-p = 'move-node-to-workspace P'
alt-shift-w = 'move-node-to-workspace W'

alt-tab = 'workspace-back-and-forth'

# SERVICE MODE
alt-shift-semicolon = 'mode service'


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
